### ISSUE TITLE
Amazon Q doesn't support brand new ghostty terminal

### ISSUE THREAD

**Issue by hossein-nas** [aws/amazon-q-developer-cli#338] opened 2024-12-31 19:16 UTC
### Checks

- [X] I have searched [github.com/aws/amazon-q-developer-cli/issues](https://github.com/aws/amazon-q-developer-cli/issues?q=) and there are no duplicates of my issue
- [X] I have run `q doctor` in the affected terminal session
- [X] I have run `q restart` and replicated the issue again

### Operating system

macOS 15.2.0 (24C101)

### Expected behaviour

Amazon q should support Ghostty terminal like Iterm2

### Actual behaviour

Amazon q doesn't support Ghostty terminal like Iterm2

### Environment

```yaml
[q-details]
version = "1.5.1"
hash = "43f92e418e96c7beaa3e881f299241c15ba65900"
date = "2024-12-13T00:53:22.005531Z (19d ago)"
variant = "full"

[system-info]
os = "macOS 15.2.0 (24C101)"
chip = "Apple M2 Pro"
total-cores = 12
memory = "32.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER"
os = "Mac"
shell-path = "/bin/zsh"
shell-version = "5.9"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.sdkman/candidates/java/current/bin:/opt/homebrew/opt/openjdk@17/bin:/opt/homebrew/opt/openssl@1.1/bin:/Users/USER/.gem/bin:/opt/homebrew/opt/ruby/bin:/Users/USER/.bun/bin:/Users/USER/.volta/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/Users/USER/.cargo/bin:/Applications/Ghostty.app/Contents/MacOS:/Users/USER/.local/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scripts:/Users/USER/flutter/bin:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/Library/Android/sdk/tools:/Users/USER/Library/Android/sdk/tools/bin:/Users/USER/Library/Android/sdk/emulator"
QTERM_SESSION_ID = "f7c804e58ef8434c99aedc158a2bac66"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.5.1"
SHELL = "/bin/zsh"
TERM = "xterm-ghostty"
__CFBundleIdentifier = "com.mitchellh.ghostty"
```

**Comment by grant0417** [comment] 2024-12-31 22:18
Closing this as duplicate of #323

**Closed by grant0417** 2024-12-31 22:18 UTC

**Comment by grant0417** [comment] 2025-01-09 19:10
The 1.6.0 release of Amazon Q has been released with support for Ghostty
